"""
This Streamlit page displays the privacy policy for the Rickbot application.
It outlines how user data is handled, emphasizing that no personal data, prompts,
or responses are collected or stored.
"""

import streamlit as st

st.set_page_config(
    page_title="Privacy Policy",
    page_icon="🔒",
    layout="centered",
)

st.title("🔒 Privacy Policy")

st.markdown("""
This Privacy Policy describes how Rickbot ("we," "us," or "our") collects, uses, and discloses your information when you use our Streamlit application ("Rickbot").

**1. Information We Do Not Collect**

Rickbot is designed with your privacy in mind. We do not collect, store, or process any personal data, prompts, or responses from your interactions with the chatbot. All conversations are ephemeral and are not retained on our servers or any third-party services.

**2. How Your Data is Handled (Ephemeral)**

When you interact with Rickbot:
*   **Prompts**: Your input prompts are sent to the Google Gemini API for processing. These prompts are used solely to generate a response and are not stored by Rickbot.
*   **Responses**: The responses generated by the Google Gemini API are displayed to you in real-time. These responses are not stored by Rickbot.
*   **Attachments**: If you upload files (images, videos, etc.), they are temporarily processed for the current interaction with the Google Gemini API and are not stored by Rickbot after the interaction.

**3. Third-Party Services**

Rickbot utilizes the Google Gemini API for its core functionality. Your prompts and attachments are sent to this API for processing. Please refer to Google's privacy policy for information on how they handle data.

**4. Rate Limiting**

To ensure fair usage and prevent abuse, Rickbot implements a simple in-memory rate limiting mechanism. This mechanism tracks the number of requests from a session within a given time frame. This data is not personally identifiable and is not stored persistently.

**5. Changes to This Privacy Policy**

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.

**6. Contact Us**

If you have any questions about this Privacy Policy, please contact the developer via the GitHub repository linked on the main page.

---
*Last updated: June 26, 2025*
""")
