import * as React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { Box, Typography, Container, Button, Paper, Divider } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#90caf9',
    },
    secondary: {
      main: '#f48fb1',
    },
    background: {
        default: '#121212',
        paper: '#1e1e1e'
    }
  },
  typography: {
      fontFamily: 'Courier New, monospace',
  }
});

export default function PrivacyPolicy() {
  return (
    <ThemeProvider theme={darkTheme}>
      <CssBaseline />
      <Head>
        <title>Privacy Policy - Rickbot</title>
        <meta name="description" content="Privacy Policy for Rickbot" />
      </Head>
      
      <Container maxWidth="md" sx={{ py: 8 }}>
        <Paper elevation={3} sx={{ p: 4, bgcolor: 'rgba(30,30,30,0.9)' }}>
          <Box sx={{ mb: 4, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <Typography variant="h3" color="primary">
               Privacy Policy
            </Typography>
            <Link href="/" passHref legacyBehavior>
                <Button variant="outlined" startIcon={<ArrowBackIcon />}>
                    Back to Chat
                </Button>
            </Link>
          </Box>
          
          <Divider sx={{ mb: 4 }} />

          <Typography variant="body1" paragraph>
            This Privacy Policy describes how Rickbot ("we," "us," or "our") collects, uses,
            and discloses your information when you use our application ("Rickbot").
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            1. Information We Do Not Collect
          </Typography>
          <Typography variant="body1" paragraph>
            Rickbot is designed with your privacy in mind. We do not collect, store, or
            process any personal data, prompts, or responses from your interactions with the
            chatbot. All conversations are ephemeral and are not retained on our servers or
            any third-party services.
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            2. How Your Data is Handled (Ephemeral)
          </Typography>
          <Typography variant="body1" component="div">
            When you interact with Rickbot:
            <ul>
              <li><strong>Prompts</strong>: Your input prompts are sent to the Google Gemini API for processing. These prompts are used solely to generate a response and are not stored by Rickbot.</li>
              <li><strong>Responses</strong>: The responses generated by the Google Gemini API are displayed to you in real-time. These responses are not stored by Rickbot.</li>
              <li><strong>Attachments</strong>: If you upload files (images, videos, etc.), they are temporarily processed for the current interaction with the Google Gemini API and are not stored by Rickbot after the interaction.</li>
            </ul>
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            3. Third-Party Services
          </Typography>
          <Typography variant="body1" paragraph>
            Rickbot utilizes the Google Gemini API for its core functionality. Your prompts
            and attachments are sent to this API for processing. Please refer to Google's
            privacy policy for information on how they handle data.
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            4. Rate Limiting
          </Typography>
          <Typography variant="body1" paragraph>
            To ensure fair usage and prevent abuse, Rickbot implements a simple in-memory
            rate limiting mechanism. This mechanism tracks the number of requests from a
            session within a given time frame. This data is not personally identifiable and
            is not stored persistently.
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            5. Changes to This Privacy Policy
          </Typography>
          <Typography variant="body1" paragraph>
            We may update our Privacy Policy from time to time. We will notify you of any
            changes by posting the new Privacy Policy on this page. You are advised to
            review this Privacy Policy periodically for any changes.
          </Typography>

          <Typography variant="h5" color="secondary" gutterBottom sx={{ mt: 4 }}>
            6. Contact Us
          </Typography>
          <Typography variant="body1" paragraph>
            If you have any questions about this Privacy Policy, please contact the
            developer via the GitHub repository linked on the main page.
          </Typography>

          <Divider sx={{ my: 4 }} />
          <Typography variant="caption" display="block" textAlign="center">
            Last updated: December 29, 2025
          </Typography>
        </Paper>
      </Container>
    </ThemeProvider>
  );
}
