steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        if [ "$_UI_TYPE" = "react" ]; then
          echo "Deploying React Sidecar architecture to Production..."
          
          cat <<EOF > service.yaml
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: $_SERVICE_NAME
          annotations:
            run.googleapis.com/ingress: all
            run.googleapis.com/launch-stage: BETA
        spec:
          template:
            metadata:
              annotations:
                run.googleapis.com/execution-environment: gen2
                run.googleapis.com/startup-cpu-boost: 'true'
            spec:
              serviceAccountName: $_SERVICE_NAME-app-sa@$_PROD_PROJECT_ID.iam.gserviceaccount.com
              containers:
              - name: ingress
                image: $_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-react-fe:$SHORT_SHA
                ports:
                - containerPort: 3000
                resources:
                  limits:
                    cpu: '1'
                    memory: 2Gi
                env:
                - name: NEXT_PUBLIC_API_URL
                  value: http://localhost:8000
                - name: NEXTAUTH_URL
                  value: $_APP_URL
              - name: api-sidecar
                image: $_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-api-sidecar:$SHORT_SHA
                resources:
                  limits:
                    cpu: '2'
                    memory: 4Gi
                env:
                - name: GOOGLE_CLOUD_PROJECT
                  value: $_PROD_PROJECT_ID
                - name: GOOGLE_CLOUD_REGION
                  value: $_REGION
                - name: LOG_LEVEL
                  value: $_LOG_LEVEL
                - name: APP_NAME
                  value: $_APP_NAME
                - name: AGENT_NAME
                  value: $_AGENT_NAME
                - name: GOOGLE_GENAI_USE_VERTEXAI
                  value: "$_GOOGLE_GENAI_USE_VERTEXAI"
                - name: MODEL
                  value: "$_MODEL"
                - name: AUTH_REQUIRED
                  value: "$_AUTH_REQUIRED"
                - name: RATE_LIMIT
                  value: "$_RATE_LIMIT"
                - name: GOOGLE_CLOUD_LOCATION
                  value: "$_GOOGLE_CLOUD_LOCATION"
        EOF
          gcloud beta run services replace service.yaml --project=$_PROD_PROJECT_ID --region=$_REGION
        else
          echo "Deploying Streamlit (Legacy) architecture to Production..."
          gcloud run deploy "$_SERVICE_NAME" \
            --image="$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-streamlit:$SHORT_SHA" \
            --region="$_REGION" \
            --project="$_PROD_PROJECT_ID" \
            --max-instances=$_MAX_INSTANCES \
            --cpu-boost \
            --set-env-vars="GOOGLE_CLOUD_PROJECT=$_PROD_PROJECT_ID,GOOGLE_CLOUD_REGION=$_REGION,LOG_LEVEL=$_LOG_LEVEL,APP_NAME=$_APP_NAME,AGENT_NAME=$_AGENT_NAME,GOOGLE_GENAI_USE_VERTEXAI=$_GOOGLE_GENAI_USE_VERTEXAI,MODEL=$_MODEL,AUTH_REQUIRED=$_AUTH_REQUIRED,RATE_LIMIT=$_RATE_LIMIT,GOOGLE_CLOUD_LOCATION=$_GOOGLE_CLOUD_LOCATION" \
            --service-account="$_SERVICE_NAME-app-sa@$_PROD_PROJECT_ID.iam.gserviceaccount.com" \
            --allow-unauthenticated
        fi

# Note: The values defined here act as defaults.
# They are overridden by substitutions defined in the Cloud Build Trigger (Highest Priority).
substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: europe-west4
  _ARTIFACT_REPO_NAME: rickbot-adk
  _SERVICE_NAME: rickbot-adk
  _APP_NAME: rickbot_st_ui
  _AGENT_NAME: rickbot_agent
  _LOG_LEVEL: INFO
  _GOOGLE_GENAI_USE_VERTEXAI: "True"
  _MODEL: "gemini-2.5-flash"
  _AUTH_REQUIRED: "True"
  _RATE_LIMIT: "120"
  _GOOGLE_CLOUD_LOCATION: "global"
  _MAX_INSTANCES: "1"
  _UI_TYPE: "react"
  _APP_URL: "https://rickbot.co.uk"

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
