steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - "./scripts/deploy-prod.sh"

# Note: The values defined here act as defaults.
# They are overridden by substitutions defined in the Cloud Build Trigger (Highest Priority).
substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: europe-west4
  _ARTIFACT_REPO_NAME: rickbot-adk
  _SERVICE_NAME: rickbot-adk
  _APP_NAME: rickbot_st_ui
  _AGENT_NAME: rickbot_agent
  _LOG_LEVEL: INFO
  _GOOGLE_GENAI_USE_VERTEXAI: "True"
  _MODEL: "gemini-2.5-flash"
  _AUTH_REQUIRED: "True"
  _RATE_LIMIT: "120"
  _GOOGLE_CLOUD_LOCATION: "global"
  _MAX_INSTANCES: "1"
  _UI_TYPE: "react"
  _APP_URL: "https://rickbot.co.uk"

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
