steps:
  # Install uv package manager and sync dependencies
  - name: "python:3.11-slim"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv==0.6.12 --user && uv sync --locked
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Run unit tests using pytest
  - name: "python:3.11-slim"
    id: unit-tests
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv run pytest src/tests/unit
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Run integration tests
  # - name: "python:3.11-slim"
  #   id: integration-tests
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       uv run pytest src/tests/integration
  #   env:
  #     - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Run frontend tests (React/Next.js)
  - name: "node:20-slim"
    id: frontend-tests
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        cd src/nextjs_fe && npm ci && npm test

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
