steps:
  # Build and push with Kaniko
  - name: "gcr.io/kaniko-project/executor:latest"
    id: build-and-push
    args:
      - "--destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
      - "--destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME:latest"
      - "--context=."
      - "--dockerfile=./Dockerfile.unified"
      - "--cache=true"
      - "--cache-ttl=48h"
      - "--build-arg=COMMIT_SHA=$COMMIT_SHA"

  # Deploy to Staging
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-staging
    entrypoint: gcloud
    args:
      - "beta"
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--project=${_STAGING_PROJECT_ID}"
      - '--min-instances=$_MIN_INSTANCES'
      - '--max-instances=$_MAX_INSTANCES'
      - '--cpu-boost'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$_STAGING_PROJECT_ID,GOOGLE_CLOUD_REGION=$_REGION,LOG_LEVEL=$_LOG_LEVEL,APP_NAME=$_APP_NAME,AGENT_NAME=$_AGENT_NAME,GOOGLE_GENAI_USE_VERTEXAI=$_GOOGLE_GENAI_USE_VERTEXAI,MODEL=$_MODEL,AUTH_REQUIRED=$_AUTH_REQUIRED,RATE_LIMIT=$_RATE_LIMIT,GOOGLE_CLOUD_LOCATION=$_GOOGLE_CLOUD_LOCATION,GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID,GITHUB_CLIENT_ID=$_GITHUB_CLIENT_ID,NEXTAUTH_URL=$_NEXTAUTH_URL'
      - '--service-account=$_SERVICE_NAME-app-sa@$_STAGING_PROJECT_ID.iam.gserviceaccount.com'
      - '--allow-unauthenticated' # Allow unauthenticated invocations - end user needs IAP-secured Web App User role (roles/iap.httpsResourceAccessor)
      # - '--iap' # Enable direct IAP
      - '--set-secrets=GOOGLE_API_KEY=gemini-api-key:latest,NEXTAUTH_SECRET=nextauth-secret:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GITHUB_CLIENT_SECRET=github-client-secret:latest'

  # Fetch Staging Service URL
  - name: "gcr.io/cloud-builders/gcloud"
    id: fetch-staging-url
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $(gcloud run services describe rickbot-adk \
        --region ${_REGION} --project ${_STAGING_PROJECT_ID} --format="value(status.url)") > staging_url.txt

  # Fetch ID Token
  - name: gcr.io/cloud-builders/gcloud
    id: fetch-id-token
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $(gcloud auth print-identity-token -q) > id_token.txt

  # Trigger Prod Deployment
  - name: gcr.io/cloud-builders/gcloud
    id: trigger-prod-deployment
    entrypoint: gcloud
    args:
      - "beta"
      - "builds"
      - "triggers"
      - "run"
      - "deploy-rickbot-adk"
      - "--region=$_CB_REGION" # Use the specific region where the Cloud Build trigger is located
      - "--project=$PROJECT_ID"
      - "--sha=$COMMIT_SHA"

  - name: gcr.io/cloud-builders/gcloud
    id: echo-view-build-trigger-link
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "_________________________________________________________________________"
        echo "Production deployment triggered. View progress and / or approve on the Cloud Build Console:"
        echo "https://console.cloud.google.com/cloud-build/builds;region=$_CB_REGION"
        echo "_________________________________________________________________________"

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _STAGING_PROJECT_ID: YOUR_STAGING_PROJECT_ID
  _CB_REGION: europe-west1 # The region where the Cloud Build trigger is located
  _REGION: europe-west4
  _AR_HOSTNAME: europe-west4-docker.pkg.dev
  _ARTIFACT_REPO_NAME: rickbot-adk
  _SERVICE_NAME: rickbot-adk
  _APP_NAME: rickbot_react
  _AGENT_NAME: rickbot_agent
  _LOG_LEVEL: DEBUG
  _GOOGLE_GENAI_USE_VERTEXAI: "False"
  _MODEL: "gemini-2.5-flash"
  _AUTH_REQUIRED: "False"
  _RATE_LIMIT: "60"
  _GOOGLE_CLOUD_LOCATION: "global"
  _MAX_INSTANCES: "1"
  _MIN_INSTANCES: "0"
  _GOOGLE_CLIENT_ID: "trigger-override-required"
  _GITHUB_CLIENT_ID: "trigger-override-required"
  _NEXTAUTH_URL: "trigger-override-required"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - rickbot-adk