steps:
  # 1. Build Streamlit (Legacy)
    # Only run if UI_TYPE is streamlit
    script: |
      #!/usr/bin/env bash
      if [ "$_UI_TYPE" == "streamlit" ]; then
        /kaniko/executor \
        --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-streamlit:$SHORT_SHA \
        --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-streamlit:latest \
        --context=. \
        --dockerfile=./Dockerfile \
        --cache=true \
        --cache-ttl=48h \
        --build-arg=COMMIT_SHA=$COMMIT_SHA
      else
        echo "Skipping Streamlit build as _UI_TYPE is $_UI_TYPE"
      fi
    automapSubstitutions: true

  # 2. Build React FE (Sidecar Ingress)
  - name: "gcr.io/kaniko-project/executor:latest"
    id: build-react-fe
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_UI_TYPE" = "react" ]; then
          /kaniko/executor \
          --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-react-fe:$SHORT_SHA \
          --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-react-fe:latest \
          --context=. \
          --dockerfile=./Dockerfile.react_fe \
          --cache=true \
          --cache-ttl=48h \
          --build-arg=COMMIT_SHA=$COMMIT_SHA
        else
          echo "Skipping React FE build as _UI_TYPE is $_UI_TYPE"
        fi

  # 3. Build API Sidecar
  - name: "gcr.io/kaniko-project/executor:latest"
    id: build-api-sidecar
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$_UI_TYPE" = "react" ]; then
          /kaniko/executor \
          --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-api-sidecar:$SHORT_SHA \
          --destination=$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-api-sidecar:latest \
          --context=. \
          --dockerfile=./Dockerfile.api_sidecar \
          --cache=true \
          --cache-ttl=48h \
          --build-arg=COMMIT_SHA=$COMMIT_SHA
        else
          echo "Skipping API Sidecar build as _UI_TYPE is $_UI_TYPE"
        fi

  # 4. Deploy to Staging (Conditional)
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-staging
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        # Define common environment variables
        export COMMON_ENV_VARS="
        - name: GOOGLE_CLOUD_PROJECT
          value: "$_STAGING_PROJECT_ID"
        - name: GOOGLE_CLOUD_REGION
          value: "$_REGION"
        - name: LOG_LEVEL
          value: "$_LOG_LEVEL"
        - name: APP_NAME
          value: "$_APP_NAME"
        - name: AGENT_NAME
          value: "$_AGENT_NAME"
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "$_GOOGLE_GENAI_USE_VERTEXAI"
        - name: MODEL
          value: "$_MODEL"
        - name: AUTH_REQUIRED
          value: "$_AUTH_REQUIRED"
        - name: RATE_LIMIT
          value: "$_RATE_LIMIT"
        - name: GOOGLE_CLOUD_LOCATION
          value: "$_GOOGLE_CLOUD_LOCATION"
        "
        
        # Define common environment variables (Flags format for Streamlit)
        export COMMON_ENV_FLAGS="GOOGLE_CLOUD_PROJECT=$_STAGING_PROJECT_ID,GOOGLE_CLOUD_REGION=$_REGION,LOG_LEVEL=$_LOG_LEVEL,APP_NAME=$_APP_NAME,AGENT_NAME=$_AGENT_NAME,GOOGLE_GENAI_USE_VERTEXAI=$_GOOGLE_GENAI_USE_VERTEXAI,MODEL=$_MODEL,AUTH_REQUIRED=$_AUTH_REQUIRED,RATE_LIMIT=$_RATE_LIMIT,GOOGLE_CLOUD_LOCATION=$_GOOGLE_CLOUD_LOCATION"

        if [ "$_UI_TYPE" = "react" ]; then
          echo "Deploying React Sidecar architecture..."
          # Note: We use 'gcloud alpha run deploy' or a YAML for multi-container
          # For simplicity and reliability, we'll use a YAML template.
          
          cat <<EOF > service.yaml
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: $_SERVICE_NAME
          annotations:
            run.googleapis.com/ingress: all
            run.googleapis.com/launch-stage: BETA
        spec:
          template:
            metadata:
              annotations:
                run.googleapis.com/execution-environment: gen2
                run.googleapis.com/startup-cpu-boost: 'true'
            spec:
              serviceAccountName: $_SERVICE_NAME-app-sa@$_STAGING_PROJECT_ID.iam.gserviceaccount.com
              containers:
              - name: ingress
                image: $_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-react-fe:$SHORT_SHA
                ports:
                - containerPort: 3000
                resources:
                  limits:
                    cpu: '0.2'
                    memory: 512Mi
                env:
                - name: NEXT_PUBLIC_API_URL
                  value: http://localhost:8000
                - name: NEXTAUTH_URL
                  value: $_APP_URL
              - name: api-sidecar
                image: $_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-api-sidecar:$SHORT_SHA
                resources:
                  limits:
                    cpu: '0.8'
                    memory: 1536Mi
                env:
$COMMON_ENV_VARS
        EOF
          gcloud beta run services replace service.yaml --project=$_STAGING_PROJECT_ID --region=$_REGION
          
          # Enable IAP for Staging
          gcloud run services update "$_SERVICE_NAME" --project=$_STAGING_PROJECT_ID --region=$_REGION --iap
        else
          echo "Deploying Streamlit (Legacy) architecture..."
          gcloud run deploy "$_SERVICE_NAME" \
            --image="$_AR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_SERVICE_NAME-streamlit:$SHORT_SHA" \
            --region="${_REGION}" \
            --project="${_STAGING_PROJECT_ID}" \
            --max-instances=$_MAX_INSTANCES \
            --cpu-boost \
            --set-env-vars="$COMMON_ENV_FLAGS" \
            --service-account="$_SERVICE_NAME-app-sa@$_STAGING_PROJECT_ID.iam.gserviceaccount.com" \
            --iap
        fi

  # Fetch Staging Service URL
  - name: "gcr.io/cloud-builders/gcloud"
    id: fetch-staging-url
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $(gcloud run services describe rickbot-adk \
        --region ${_REGION} --project ${_STAGING_PROJECT_ID} --format="value(status.url)") > staging_url.txt

  # Fetch ID Token
  - name: gcr.io/cloud-builders/gcloud
    id: fetch-id-token
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $(gcloud auth print-identity-token -q) > id_token.txt

  # Load Testing
  # - name: "python:3.11-slim"
  #   id: load_test
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       export _ID_TOKEN=$(cat id_token.txt)
  #       export _STAGING_URL=$(cat staging_url.txt)
  #       pip install locust==2.31.1 --user
  #       locust -f src/tests/load_test/load_test.py \
  #       --headless \
  #       -H $$_STAGING_URL \
  #       -t 30s -u 10 -r 0.5 \
  #       --csv=src/tests/load_test/.results/results \
  #       --html=src/tests/load_test/.results/report.html
  #   env:
  #     - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Export Load Test Results to GCS
  # - name: gcr.io/cloud-builders/gcloud
  #   id: export-results-to-gcs
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       export _TIMESTAMP=$(date +%Y%m%d-%H%M%S)
  #       gsutil -m cp -r src/tests/load_test/.results gs://${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}
  #       echo "_________________________________________________________________________"
  #       echo "Load test results copied to gs://${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}"
  #       echo "HTTP link: https://console.cloud.google.com/storage/browser/${_BUCKET_NAME_LOAD_TEST_RESULTS}/results-$${_TIMESTAMP}"
  #       echo "_________________________________________________________________________"

  # Trigger Prod Deployment
  - name: gcr.io/cloud-builders/gcloud
    id: trigger-prod-deployment
    entrypoint: gcloud
    args:
      - "beta"
      - "builds"
      - "triggers"
      - "run"
      - "deploy-rickbot-adk"
      - "--region=$_CB_REGION" # Use the specific region where the Cloud Build trigger is located
      - "--project=$PROJECT_ID"
      - "--sha=$COMMIT_SHA"

  - name: gcr.io/cloud-builders/gcloud
    id: echo-view-build-trigger-link
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "_________________________________________________________________________"
        echo "Production deployment triggered. View progress and / or approve on the Cloud Build Console:"
        echo "https://console.cloud.google.com/cloud-build/builds;region=$_CB_REGION"
        echo "_________________________________________________________________________"

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _STAGING_PROJECT_ID: YOUR_STAGING_PROJECT_ID
  _CB_REGION: europe-west1 # The region where the Cloud Build trigger is located
  _REGION: europe-west4
  _AR_HOSTNAME: europe-west4-docker.pkg.dev
  _ARTIFACT_REPO_NAME: rickbot-adk
  _SERVICE_NAME: rickbot-adk
  _APP_NAME: rickbot_st_ui
  _AGENT_NAME: rickbot_agent
  _LOG_LEVEL: DEBUG
  _GOOGLE_GENAI_USE_VERTEXAI: "True"
  _MODEL: "gemini-2.5-flash"
  _AUTH_REQUIRED: "False"
  _RATE_LIMIT: "120"
  _GOOGLE_CLOUD_LOCATION: "global"
  _MAX_INSTANCES: "1"
  _UI_TYPE: "react"
  _APP_URL: "https://staging.rickbot.co.uk"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - rickbot-adk 